export const ColorsTheme = {
  primary: "#efab46",
  secondary: "#1F5152",
  secondaryDark: "#1d484b",
  secondaryDarkTransparent: "rgba(29,72,75, .75)",
  secondaryLight: "#387778",
  secondaryLightest: "#f0f5f5",
  tertiary: "#000",
  background: "#FFF",
  buttonDisabled: "#bababa",
  textOnPrimary: "#000",
  textOnSecondary: "#FFF",
  textOnTertiary: "#FFF",
  textOnBackground: "#000",
  textOnDisabled: "#828282",
  separator: "#ececec",
};
